### ISSUE TITLE
ファイル名・役割の整理について

### ISSUE THREAD

**Issue by 0918nobita** [0918nobita/Tea-tango#10]
単語帳の編集画面や問題の投稿画面を開発しているうちに、ファイル名もその役割も曖昧になってきています。
なので、ここでいったん整理すべきだと思います。自分なりにまとめてみましたが、どうでしょう？

index.php(トップページ・タイムライン)アクティビティを表示。ログインしていなかったらlogin.phpに飛ばす。
eitango.css(スタイルシート)
eitango_header.php(旧eitango_header.js)PHPファイルにすることで、ログインしている時としていない時で表示を変更できる。
eitango_about.php(Tea-tangoとは？)
eitango_help.php(Q&A)
functions.php(関数)
config.php(定数・パスワード)
signup.php(ユーザー登録画面)
login.php(ログイン画面)
logout.php(ログアウト処理)
wordcard.php(単語帳詳細画面)単語帳の作成者自身はここで単語帳の削除が可能
wordcard_add.php(単語帳作成画面)非公開設定可能
wordcard_edit.php(単語帳編集画面)非公開設定編集可能
card.php(問題詳細画面)問題の投稿者自身はここで問題の削除が可能
card_add.php(問題投稿画面)
card_edit.php(問題編集画面)
profile.php(プロフィール画面)自分のプロフィールを表示しているときのみプロフィール編集ボタンを表示
profile_edit.php(プロフィール編集画面)退会処理はここで行えるようにする
notice.php(運営からのお知らせ)
performance.php(成績画面)performanceテーブルのデータをもとに成績を視覚表示
my_wordcards.php(マイ単語帳)自分が過去に作成した単語帳・自分がお気に入り追加した他のユーザーの単語帳・最近使用した他のユーザーの単語帳が表示される。

**Comment by afuafu55** [comment]
これだけのページがあると MVC を実装したほうが管理しやすいと思います。

**Comment by afuafu55** [comment]
MVCを実装するには Smarty のようなテンプレートエンジンがあったほうがいいです。
使いますか？

**Comment by 0918nobita** [comment]
使うことにします。
ですがユーザー側からすると、ページを新規に読み込む回数が多いのはストレスになると思います。実際、スマホからネットサーフィンしている人はみな通信料を気にします。なので、それを実装する前になるべくまとめられるページはまとめて、読み込む回数を減らすべきだと思います。例えばいちいち投稿ページにリンクするのではなくPHP側でrequireで予め投稿フォームのPHPを読み込んでおき、display:noneの状態にしておき、投稿ボタンを押された時にjQuery等で表示アニメーションを使うとか。

**Comment by afuafu55** [comment]
いいと思います
もう View (Smartyのテンプレート) を作り始めています。
MVC 　の実装を先にしませんか？

**Comment by 0918nobita** [comment]
お願いします
あっ、先ほど新しいヘッダーが完成しました。
操作性が向上してるので
http://ttan5.zz.vc/test
ここで確認してください
MVCの件が終わってからこれを適用しようと思います。

**Comment by 0918nobita** [comment]
ヘッダーとサイドメニューは固定されるように変更しておきます。

**Comment by afuafu55** [comment]
Smarty に{include} などの機能があるのでヘッダはそこでしようと思います

**Comment by 0918nobita** [comment]
少し開発休みます
Smartyについて勉強してきます
