### ISSUE TITLE
ログインページで500エラー(旧：ログアウトページが表示できない)

### ISSUE THREAD

**Issue by 0918nobita** [0918nobita/Tea-tango#57]
othersページにリンクを貼ってあるログアウトページに飛ぶと、なぜかなにも表示されなくなり、リダイレクトも実行されません。

**Comment by grainrigi** [comment]
単純にloginのほうで500エラーになってるだけみたいです
その原因はよくわかりませんが・・・

**Comment by 0918nobita** [comment]
最新コミットで、login.phpのコードにsetCookie関数を追加して、自動ログイン機能を追加しようとしているところなので、もしかしたらCookie関連のコードを修正すれば治るかもしれません

**Comment by 0918nobita** [comment]
自動ログイン機能はいまは実装しないほうが安全なのでCookie関連のコードは一度消しました。
ヘッダのボタンに貼ったリンクがおかしかったみたいです。そこを修正すると治りました
