### ISSUE TITLE
テンプレートファイルが表示されない

### ISSUE THREAD

**Issue by 0918nobita** [0918nobita/Tea-tango#59]
現在MVC-fixブランチの、testフォルダ内でObjective-PHPを参考にしながらMVCを実装するテストをしていますが、test/controllers/AboutController.php内で定義しているAboutControllerクラスのdisplayActionメソッドの処理で$this->display('about.tpl');としてもabout.tplが出力されません。こん

**Comment by 0918nobita** [comment]
コンストラクタで$this->viewをSmaryクラスのインスタンスにしているので、$this->view->template_dir = "〜"辺りが怪しいですが…

**Comment by grainrigi** [comment]
問題を修正しました。
原因は、Smartyのインクルードの相対パスの記述ミスと、footer.tplのミッシングだったようです。

一応issueは閉じずに残しておきますので、exoutのほうで動作確認でき次第閉じてやってください。

**Comment by 0918nobita** [comment]
ありがとうございます！
了解です(･o･)ゞ
