### ISSUE TITLE
コーディング規約について

### ISSUE THREAD

**Issue by afuafu55** [0918nobita/Tea-tango#6]
例えば関数名での単語の区切りを大文字小文字にする/アンダースコアにするなど
コーディングのルールを簡単に決めませんか？

**Comment by 0918nobita** [comment]
すべて小文字では読みにくいので、connectDbのように、先頭の文字以外の単語の切れ目では大文字にするようにすればいいと思います。javascriptのソースコードでよく見る書き方です。

**Comment by afuafu55** [comment]
変数名・関数名 などではそれでいきましょう
