### ISSUE TITLE
ログイン処理の記述位置について

### ISSUE THREAD

**Issue by 0918nobita** [0918nobita/Tea-tango#60]
現在MVC-fixブランチで開発を続けていますが、

Userコントローラ…profileビュー or profileEditビューの呼び出し
Userモデル…getUserByName()でユーザー情報をまとめた連想配列を返す
profileビュー…プロフィール画面
profileEditビュー…プロフィール編集画面

今のところこんなかんじに分担してコードを書いてます

ところで、ログイン処理(ロジック)を書くべき場所はUserモデルでしょうか？それとも、他の場所に書くべきでしょうか？

**Comment by grainrigi** [comment]
Userモデルでいいと思います
モデル自体はコントローラーから呼び出されるのがよろしいかと思います
ただ、私はMVCには疎いのでこれが正しいのかどうかはよくわかりませんが・・・

**Comment by 0918nobita** [comment]
了解です
とりあえずはそれでいきましょう

**Comment by 0918nobita** [comment]
了解です
とりあえずはそれでいきましょう
