### ISSUE TITLE
パスワードの暗号化アルゴリズムについて

### ISSUE THREAD

**Issue by 0918nobita** [0918nobita/Tea-tango#61]
materブランチのsignup.php, login.phpでは、sha1暗号化アルゴリズムを使用してパスワードを暗号化した上でサインアップ処理・ログイン処理をしていましたが、sha1暗号化アルゴリズムには脆弱性があるため、ほかのアルゴリズムに切り替える必要が出てきました。とりあえず今は暗号化せずにパスワードを扱うようにコードを書いています。どの暗号化アルゴリズムを使うべきなのか、ここで検討しようと思います。

**Comment by grainrigi** [comment]
スタンダードにsha-2なんてどうでしょうか
ハッシュ長は512ビットでいいかと思います

**Comment by 0918nobita** [comment]
調べてみましたが確かにsha2のビット長512が一番良さげですね。それでいきましょう
