### ISSUE TITLE
ログイン処理におけるユーザー名、メールアドレスの分岐について

### ISSUE THREAD

**Issue by grainrigi** [0918nobita/Tea-tango#62]
大した問題でもないんですが、現状の実装ではユーザーIDが有効なメールアドレスの形式をとっていた場合にログインできないという問題があるので、以下のどちらかの実装の変更したほうが良いかと思います

・ユーザーIDに@マークなどの記号を含めることができないようにする
・ログイン時に入力された文字列と一致するメールアドレスがなかった場合に、ユーザーIDを参照するようにする

個人的には前者のほうが良いかと思いますが、ご意見よろしくお願いします

**Comment by 0918nobita** [comment]
ユーザー情報としては、

id … ユーザーごとに異なる数値が割り当てられます。(オートインクリメントを設定してあります)
name … 登録後変更のできない名前です。ツイッターでいうところの『@〜』のほうです。
screen_name … 登録後でも変更できる、実際にタイムラインなどで表示される名前です。こちらのほうがnameより強調表示になります。
profile … 自己紹介文です。
created … アカウントの作成日時です。
modified … アカウント情報の最終更新日時です。

このようになっていますが、ログイン時に『ユーザーID』として入力できるのは登録後変更のできないnameになります。
先頭に@つけるなどの形式についてはまだ決まっていませんが、アカウント作成時にフォームでの入力情報確認で、nameは半角英数字とアンダーバー以外の文字を含んでいれば作成できないようにするつもりです。
つまり半角英数字・アンダーバーのみを含むユーザーID(name)で登録するようにアカウント作成画面で入力情報確認を行う、ということです。

ちなみにjavascriptでフォームの入力情報を確認することはもちろんできますが、ユーザーが利用しているブラウザが古いあるいはjavascriptがオフになっている場合も考えられるので、サーバーにPOSTされてからPHPでも入力情報確認を行うようにするのが一般的です。

**Comment by grainrigi** [comment]
詳細な指針ありがとうございます。

おっしゃる通り、データ確認はフェイルセーフの意味も込めてPHP側では必ず確認するべきですね。

ではユーザー情報に関してはここに書かれた通りの仕様で行きましょう。
