### ISSUE TITLE
Model View Controller について

### ISSUE THREAD

**Issue by afuafu55** [0918nobita/Tea-tango#8]
ロジックやユーザ・インターフェイスなどを分離できる Model View Controller (MVC) を実装しませんか？
テンプレートエンジンのSmarty を使おうと思います。

http://ja.wikipedia.org/wiki/Model_View_Controller

**Comment by 0918nobita** [comment]
別にプログラマとデザイナーが協力してやってるわけじゃないので、2人で開発している今は必要ないと思います。ただ、ログイン処理やデータベースと連携した処理はまだごちゃごちゃな感じがするので関数で簡略化する必要があると思います。(functions.phpへ追加)
eitango_header.jsには共通ヘッダーのHTMLが含まれてるので、そこを編集すればすべてのページのヘッダーに反映されます。

**Comment by afuafu55** [comment]
afuafu55/Tea-Tango の rewrite-to-the-objective で処理をまとめています。

**Comment by 0918nobita** [comment]
まずは受け取った配列をもとに自己テストができる、一番大事な復習画面(問題が表示され、ボタンを押せば答えが表示される画面)を作る必要があります。
次に、Readme.mdに書いた「今日のおすすめ」機能を追加するためにも、ユーザー情報を格納するuserテーブルに「成績」カラムを追加する必要があると思います。その列には、最近復習した問題のidを連結して可逆圧縮したものが格納されます。

**Comment by afuafu55** [comment]
成績テーブルをつくって ID ユーザID 問題ID を並べるといいと思います。

**Comment by 0918nobita** [comment]
あっ、それもそうですね。
では今のところ必要なテーブルは
・ユーザー情報のテーブル
・問題とそれに対する解答のテーブル
・単語帳の情報のテーブル
・成績データとユーザーIDのテーブル
ですね。
